[workspace]
members = [
    "bin/import",
    "bin/rest-api",
    "storage/csv-entry-storage",
    "storage/memory-index-storage",
    "storage/sled-db-entry-storage",
    "domain"
        ]

##DEFAULT RUNNING BIN
default-members=["bin/rest-api"]
#default-members=["bin/import"]
