[package]
name = "rest-api"
version = "0.1.0"
authors = ["SlackMagiC <laurent.pietrzyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
##API MANAGEMENT
actix-web = "3.1.0"
actix-rt = "1.1.1"
actix-service = "1.0.6"
actix-files = "0.4.0"
actix-cors = "0.5.0"
futures = "0.3.1"

##VARIABLES & LOGS
env_logger = "*"
dotenv = "0.15.0"

##SERIALIZATION TO JSON
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
json = "*"

##DATA UTILS => UTC Date, UUID generation
uuid = { version = "0.8.1", features = ["v5", "serde"]}
chrono = { version = "^0.4", features = ["serde"] }

##DOMAIN
domain = { path = "../../domain" }

##Memory storage
memory-index-storage = { path = "../../storage/memory-index-storage" }
sled-db-entry-storage = { path = "../../storage/sled-db-entry-storage" }